### ISSUE TITLE
Background Scan doesn't work

### ISSUE THREAD

**Issue by De-Lac** [evothings/cordova-eddystone#3] opened 2015-10-20 14:50 UTC
Hello. I can't make the scan to work on background.
I enabled background capabilities in the .plist with Xcode, specifying that the app utilizes BLE sensors.
Moreover, I use the `de.appplant.cordova.plugin.background-mode` plugin, executing after the deviceReady event the function:

``` javascript
cordova.plugins.backgroundMode.enable();
```

However the scan just pauses when entering in background mode. No matter what. Is there any alternative way? Is the background mode disabled in the eddystone plugin?
Thank you

**Comment by ghost** [comment] 2015-12-16 17:55
@De-Lac Adding iOS background mode `bluetooth-central` should enable background modes. I opened an issue for adding this to the `cordova-plugin-ble` plugin, which is used by the Eddystone plugin: https://github.com/evothings/cordova-ble/issues/85

I have no experience with the `de.appplant.cordova.plugin.background-mode` plugin. It should not be needed to enable background scanning for Eddystone beacons. However, a notification plugin is needed to actually show something when beacons are detected when running in the background.

**Comment by AceLondon** [comment] 2016-03-15 16:52
I was curious if there was any update on this? I'm trying to trigger a local notification via cordova plugin https://github.com/katzer/cordova-plugin-local-notifications from the background when a specific beacon comes in range. I added your suggested code to the ble plugin and enabled the capabilities in xcode project... but I get lost after that.

**Comment by ghost** [comment] 2016-03-15 18:23
@AceLondon The problem is that the BLE plugin does bot support background mode on iOS (this plugin: https://github.com/evothings/cordova-ble). On Android it should work with current version. An update for iOS is underway, but iOS Bluetooth background scanning has its limitations. Not occurring very frequently for example. Expect to work on iOS background mode during the coming weeks.

**Comment by AceLondon** [comment] 2016-03-22 17:17
Cool! Thanks for the quick response. I'll be following along with your progress.

**Comment by ghost** [comment] 2016-03-22 19:24
@AceLondon Hi again, the BLE plugin (https://github.com/evothings/cordova-ble) now supports background scanning on iOS and Android. On iOS you have to explicitly scan for the Eddystone service UUID (a service UUID must be specified on iOS for background scanning to work). 

Planning to to an update to the Eddystone plugin tomorrow with the functionality added.

**Comment by ghost** [comment] 2016-03-23 13:25
@AceLondon @De-Lac Just released an updated version of the plugin with support for background scanning on iOS and Android. Updated the README page with info about this and some new functions, like getting the approximate distance from the beacon.

**Comment by ghost** [comment] 2016-03-23 13:25
Closing this issue, let me know if you want to reopen it.

**Closed as completed by ghost** 2016-03-23 13:25 UTC
Labels: priority-1

**Comment by AceLondon** [comment] 2016-04-05 21:25
Great! I've been busy with other things but I am supper excited about this. I'll give it a go and get back to ya.

**Comment by ghost** [comment] 2016-04-06 06:57
@AceLondon Thanks!
